run:
  timeout: 5m
linters:
  enable:
    - asciicheck
    - depguard
    - dogsled
    - durationcheck
    - errcheck
    - errorlint
    - exportloopref
    - gci
    - gofmt
    - gofumpt
    - goimports
    - gosec
    - misspell
    - nakedret
    - nilerr
    - nolintlint
    - predeclared
    - revive
    - wastedassign
issues:
  exclude-rules:
    - linters:
        - structcheck
        - unused
      text: "`data` is unused"
    - linters:
        - staticcheck
      text: "SA1019:"
    - linters:
        - revive
      text: "var-naming:"
    - linters:
        - revive
      text: "exported:"
    - path: _test\.go
      linters:
        - gosec # security is not make sense in tests
