language: go

sudo: false

matrix:
  fast_finish: true
  include:
  - go: 1.6.x
  - go: 1.7.x
  - go: 1.8.x
  - go: 1.9.x
  - go: 1.10.x
  - go: 1.11.x
  - go: 1.11.x
    env: GO111MODULE=on
  - go: master

git:
  depth: 10

install:
  - make install

go_import_path: github.com/gin-gonic/gin

script:
  - make vet
  - make fmt-check
  - make embedmd
  - make misspell-check
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/7f95bf605c4d356372f4
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
