language: go
sudo: false
go:
  - 1.6.x
  - 1.7.x
  - 1.8.x
  - master

git:
  depth: 3

install:
  - go get -v github.com/kardianos/govendor
  - govendor sync

install:
  - test -d ${GOPATH}/bin || mkdir -p ${GOPATH}/bin
  - wget https://raw.githubusercontent.com/appleboy/golang-testing/master/coverage.sh -O ${GOPATH}/bin/coverage
  - chmod +x ${GOPATH}/bin/coverage
  # install dependency tools
  - coverage tool
  - go get -d -t -v ./...

script:
  - coverage testing
  - coverage coverage

after_success:
  - bash <(curl -s https://codecov.io/bash) -f .cover/coverage.txt

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/7f95bf605c4d356372f4
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
